# .github/labeler.yml
# Upgraded for actions/labeler@v5 structural compliance

frontend-ui:
  - changed-files:
      - any-glob-to-any-file: 
           '**/*.html'
           '**/*.css'
           'public/**/*'

javascript-logic:
  - changed-files:
      - any-glob-to-any-file: 
          - '**/*.js'

automation-scripts:
  - changed-files:
      - any-glob-to-any-file: 
          - 'backend/**/*'
          - '.github/workflows/**/*'
